#pragma once

#include <QQmlEngineExtensionPlugin>

// Deliberately minimal: the actual QML type registration for AerialManifest
// and AerialCache happens automatically via static initializers inside
// libaerial_core.so (generated by cxx-qt-build) as soon as that library is
// loaded -- which happens here as a normal DT_NEEDED dependency of this
// plugin. This class only exists so Qt's QML engine has a valid,
// dlsym()-able `QQmlEngineExtensionPlugin` to satisfy the "plugin" line in
// qmldir.
//
// This hand-written plugin exists because cxx-qt-build 0.10.0's own
// generated dynamic QML plugin entry point (`qt_plugin_instance`) gets
// compiled into the same static archive as the rest of the Rust crate, and
// Rust's default cdylib link flags (`--exclude-libs=ALL` on Linux) demote
// every symbol contributed by linked static libraries to local binding --
// including that entry point -- so Qt can never dlsym() it. Building the
// plugin class with plain CMake/AUTOMOC instead sidesteps that entirely.
class AerialWallpaperPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)
};
