# Builds the org.kde.plasma.wallpaper.aerial QML plugin as a hand-written,
# plain-CMake/AUTOMOC shared library, rather than relying on cxx-qt-build's
# own generated dynamic QML plugin entry point.
#
# Why: cxx-qt-build 0.10.0 compiles its generated plugin class (providing the
# `qt_plugin_instance` symbol Qt's QML engine dlsym()s to load a module) into
# the same static archive as the rest of the Rust crate. Rust's cdylib link
# recipe on Linux passes `-Wl,--exclude-libs=ALL`, which demotes every symbol
# contributed by a linked static archive -- including that entry point -- to
# local ELF binding, so it can never be resolved via dlsym(), even though it
# is present in the binary (verified with `nm`: global in the standalone .o,
# local after the final cdylib link; `--export-dynamic`/
# `--export-dynamic-symbol` and post-hoc `objcopy --globalize-symbol` cannot
# undo this, since --exclude-libs=ALL cannot be selectively un-excluded).
#
# The actual QML type registration for AerialManifest/AerialCache is
# unaffected by this -- it happens via static initializers that run
# automatically when libaerial_core.so is loaded, regardless of who loads it.
# So this plugin only needs to be a valid, dlsym()-able QQmlEngineExtensionPlugin
# that links against (and thus pulls in) libaerial_core.so; requires
# aerial_core to already be imported via cxx_qt_import_crate.
function(aerial_add_qml_plugin)
    if(TARGET aerial_wallpaper_qmlplugin)
        return()
    endif()

    set(module_dir "${CMAKE_BINARY_DIR}/qml_modules/org/kde/plasma/wallpaper/aerial")
    file(MAKE_DIRECTORY "${module_dir}")

    add_library(aerial_wallpaper_qmlplugin MODULE
        ${CMAKE_SOURCE_DIR}/plugin/aerial_plugin.cpp
        ${CMAKE_SOURCE_DIR}/plugin/aerial_plugin.h
    )
    set_target_properties(aerial_wallpaper_qmlplugin PROPERTIES
        LIBRARY_OUTPUT_DIRECTORY "${module_dir}"
        OUTPUT_NAME "org_kde_plasma_wallpaper_aerial_plugin"
        PREFIX "lib"
    )
    target_link_libraries(aerial_wallpaper_qmlplugin PRIVATE Qt::Qml aerial_core-shared)

    # cxx-qt-build still generates a correct plugin.qmltypes (used by
    # qmllint/IDE tooling, not required at runtime) as part of
    # cxx_qt_import_crate -- that step is unaffected by the export-visibility
    # issue above, so just reuse it instead of regenerating it ourselves.
    get_target_property(aerial_export_dir aerial_core CXX_QT_EXPORT_DIR)
    set(qmltypes_src "${aerial_export_dir}/qml_modules/org/kde/plasma/wallpaper/aerial/plugin.qmltypes")
    set(qmltypes_dst "${module_dir}/plugin.qmltypes")
    add_custom_command(
        OUTPUT "${qmltypes_dst}"
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "${qmltypes_src}" "${qmltypes_dst}"
        # `aerial_core` is Corrosion's IMPORTED (non-building) target; depend
        # on the actual driving build target so this only runs once the file
        # has really been generated by `cargo build`.
        DEPENDS cargo-build_aerial_core
        COMMENT "Copying Aerial QML plugin.qmltypes"
    )
    add_custom_target(aerial_wallpaper_qmltypes ALL DEPENDS "${qmltypes_dst}")

    file(WRITE "${module_dir}/qmldir"
"module org.kde.plasma.wallpaper.aerial
plugin org_kde_plasma_wallpaper_aerial_plugin
classname AerialWallpaperPlugin
typeinfo plugin.qmltypes
")

    set(AERIAL_QML_OUTPUT_DIR "${CMAKE_BINARY_DIR}/qml_modules" PARENT_SCOPE)
endfunction()
